app/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('',ModeloView.as_view(),name="modelo_list"),   
    path('new',ModeloNew.as_view(),name="new"),
    path('edit/<int:pk>',ModeloEdit.as_view(),name="edit"), 
    path('crud',Crud.as_view(),name="crud"),
    path('crud/update',update1,name="update1"),
    path('crud/reload',reload,name="reload"),
    path('delete/<int:pk>',ModeloDel.as_view(),name="delete"), 

    path('crud/update2',update2,name="update2"),

    path('bootstable',BootsTable.as_view(),name="bootstable"),

    path('datatable',DataTable.as_view(),name="datatable"),
    path('datatable/crud',datatable,name="datatable2"),

    path('datatable-custom',DataTableCustom.as_view(),name='datatable_custom'),

    path('bootstrap-table',BoostrapTable.as_view(),name="bootstrap_table"),
    path('crud/reload2',reload2,name="reload2"),
    path('bootstrap-table-server-side',BootstrapTableServerSide.as_view(),name="bootstrap_table_server_side"),
    path('crud/bt-serverside-load',bt_serverside_load,name="bt_serverside"),

    path('jtable/list',JTable.as_view(),name="jtable"),
    path('jtable/reload4',reload4,name="reload4"),
    path('jtable/new',jtable_new,name="jtable_new"),
    path('jtable/edit',jtable_edit,name="jtable_edit"),
    path('jtable/delete',jtable_delete,name="jtable_delete"),

    path('dt/',HWHome.as_view(),name="hwhome"),
    path('dt/hw25000_reload',hw25000_reload,name="hw25000_reload"),

    path('dt/serverside',DTServerSide.as_view(),name="dt_serverside"),
    path('dt/serverside_reload',dt_serverside,name="dt_serverside_reload"),
]

dj_deploy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include(('app.urls','app'), namespace='app')),
    path('admin/', admin.site.urls),
]

templates/bases/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Curso CRUD Dinámico con Tablas HTML</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css">
    <!-- <link rel="stylesheet" href="{% static 'Editor-2.0.9/css/editor.bootstrap5.min.css' %}"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.21.1/dist/bootstrap-table.min.css">


    <link rel="stylesheet" href="https://code.jquery.com/ui/1.13.2/themes/humanity/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'jtable.2.4.0/themes/lightcolor/green/jtable.min.css' %}">


</head>
<body>
    <div class="alert alert-dismissible alert-warning">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <h4 class="alert-heading">Atención</h4>
        <p class="mb-0">Este proyecto forma parte del curso CRUD Dinámico con Tablas HTML en Udemy, elaborado por Daniel Bojorge, <a href="https://facebook.com/debsconsultores" target="_blank" class="alert-link">Síguenos</a>.</p>
      </div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">CRUD Dinámico Tabla HTML</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'app:modelo_list' %}">Lista
                    <span class="visually-hidden">(current)</span>
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:new' %}">Nuevo</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:crud' %}">Crud</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:bootstable' %}">BootsTable</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:datatable' %}">DataTable</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:datatable_custom' %}">DataTable Custom</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:bootstrap_table' %}">Bootstrap Table</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:jtable' %}">jTable</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:hwhome' %}">HW 25000</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:dt_serverside' %}">DT ServerSide</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'app:bootstrap_table_server_side' %}">BT ServerSide</a>
                </li>
              </ul>
          </div>
        </div>
      </nav>
      <div class="container-fluid">
        <div class="row">
          {% block content%}
          {% endblock %}
        </div>
      </div>

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
      <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

      <!-- JavaScript Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

      <script src="{% static 'js/bootstable.js' %}"></script>

      <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
      <script src="https://cdn.datatables.net/buttons/2.2.3/js/dataTables.buttons.min.js"></script>
      <script src="https://cdn.datatables.net/select/1.4.0/js/dataTables.select.min.js"></script>
      <!-- <script src="https://cdn.datatables.net/datetime/1.1.2/js/dataTables.dateTime.min.js"></script> -->
      <!-- <script src="{% static 'Editor-2.0.9/js/dataTables.editor.min.js' %}"></script> -->
      <!-- <script src="{% static 'Editor-2.0.9/js/editor.bootstrap5.min.js' %}"></script> -->

      <script src="https://unpkg.com/bootstrap-table@1.21.1/dist/bootstrap-table.min.js"></script>

      <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.min.js"></script>
      <script src="{% static 'jtable.2.4.0/jquery.jtable.min.js' %}"></script>
      <script src="{% static 'jtable.2.4.0/jquery.jtable.es.js' %}"></script>


      <script>
        function mensaje(msg,titulo="",tipo="success")
        {
          Swal.fire({
            icon: tipo,
            title: titulo,
            text: msg,
            confirmButtonText: "OK"
          })
        }
      </script>
      {% block js%}{% endblock%}
</body>
</html>