app/urls.py
from django.urls import path

from .views import *


urlpatterns = [
    path('',ModeloView.as_view(),name="modelo_list"),   
    path('new',ModeloNew.as_view(),name="new"),
    path('edit/<int:pk>',ModeloEdit.as_view(),name="edit"), 
    path('crud',Crud.as_view(),name="crud"),
    path('crud/update',update1,name="update1"),
    path('crud/reload',reload,name="reload"),
    path('delete/<int:pk>',ModeloDel.as_view(),name="delete"), 

    path('crud/update2',update2,name="update2"),

    path('bootstable',BootsTable.as_view(),name="bootstable"),

    path('datatable',DataTable.as_view(),name="datatable"),
    path('datatable/crud',datatable,name="datatable2"),

    path('datatable-custom',DataTableCustom.as_view(),name='datatable_custom'),

    path('bootstrap-table',BoostrapTable.as_view(),name="bootstrap_table"),
    path('crud/reload2',reload2,name="reload2"),
    path('bootstrap-table-server-side',BootstrapTableServerSide.as_view(),name="bootstrap_table_server_side"),
    path('crud/bt-serverside-load',bt_serverside_load,name="bt_serverside"),

    path('jtable/list',JTable.as_view(),name="jtable"),
    path('jtable/reload4',reload4,name="reload4"),
    path('jtable/new',jtable_new,name="jtable_new"),
    path('jtable/edit',jtable_edit,name="jtable_edit"),
    path('jtable/delete',jtable_delete,name="jtable_delete"),

    path('dt/',HWHome.as_view(),name="hwhome"),
    path('dt/hw25000_reload',hw25000_reload,name="hw25000_reload"),

    path('dt/serverside',DTServerSide.as_view(),name="dt_serverside"),
    path('dt/serverside_reload',dt_serverside,name="dt_serverside_reload"),
]

dj_deploy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include(('app.urls','app'), namespace='app')),
    path('admin/', admin.site.urls),
]

app/templates/app/bootstable.html
{% extends 'bases/index.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-6">
      <table class="table table-hover" id="editableTable">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Código</th>
            <th scope="col">Descripción</th>
            <!-- <th scope="col">Acción</th> -->
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    
    </div>
    <div class="col-6">
      <div class="row">
        <div class="col">
          <button type="button" class="btn btn-info" id="btnReload" onclick="recargar();">Cargar</button>
          <button type="button" id="btnAdd" class="btn btn-warning">Nuevo</button>
          <button type="button" class="btn btn-primary" id="btnNewModal">Nuevo (Modal)</button>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modal_edit_new" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"  data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal_titulo">Agregar/Editar Registro</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form>
            <div class="form-group">
              <label for="idModal">Id</label>
              <input type="text" id="idModal" class="form-control" placeholder="Id" readonly>
            </div>
            <div class="form-group">
              <label for="codigoModal">Código</label>
              <input type="text" id="codigoModal" class="form-control" placeholder="Código">
            </div>
            <div class="form-group">
              <label for="descripcionModal">Descripción</label>
              <input type="text" id="descripcionModal" class="form-control" placeholder="Descripción">
            </div>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary" id="btnSaveModal">Guardar</button>
      </div>
    </div>
  </div>
</div>

{% endblock%}

{% block js%}
<script>
  $(document).ready(function(){
    recargar()
  })

  function recargar(){
    $.ajax({
        headers: {'X-CSRFToken': "{{csrf_token}}"},
        url:"{% url 'app:reload'%}",
        type:"GEST",
        success: function(r){
          console.log(r)
          datos = r.datos;
          console.log(datos)

          $("table > tbody").empty()
          var tabla = $("table")

          var rows = $.map(datos,function(value,index){
            return `<tr>
            <td>${value.id}</td><td>${value.codigo}</td>
            <td>${value.descripcion}</td>
            </tr>`
          })
          $("table > tbody").html(rows.join(''))

          $("#editableTable").find('th[name="buttons"]').remove()

          $("#editableTable").SetEditable({
            // bootstrap: false,
            columnsEd: "1,2",
            onEdit: function(cEd){
              console.log(cEd)
              if(cEd[0].childNodes[0].innerHTML==undefined){
                var i = cEd[0].childNodes[1].innerHTML
                var c = cEd[0].childNodes[2].innerHTML
                var d = cEd[0].childNodes[4].innerHTML
                // alert(c)
                // alert(d)

                var url = `edit/${i}`
                var data = {"codigo":c,"descripcion":d}
              }else{
                var i = cEd[0].childNodes[0].innerHTML
                var c = cEd[0].childNodes[1].innerHTML
                var d = cEd[0].childNodes[2].innerHTML

                var url = `{% url 'app:update1'%}`
                // var data = {"codigo":c,"descripcion":d}
                var data = {"codigo":c,"desc":d}
              }
              

              $.ajax ({
                  url : url,
                  headers: {'X-CSRFToken': "{{csrf_token}}"},
                  type: "POST",
                  data: data,
                  success: function(r){
                    // alert("Editado")
                    mensaje("Guardado Satisfatoriamente")
                  },
                  error: function(jqXHR,textStatus,error)
                  {
                    console.log(error)
                  },
                  complete: function(xhr,status){
                    console.log("Finalizada")
                    // limpiar()
                    recargar()
                  }
                })
            },
            onBeforeDelete: function(cEd){
              var i = cEd[0].childNodes[1].innerHTML
              borrar(i)
            },
            onDelete: function(){
              recargar()
            },
            $addButton: $("#btnAdd")
          })
        },
        error: function(jqXHR,textStatus,error){
          console.log(error)
        },
        complete: function(xhr,status){
          console.log("FINALIZADO")
        }
      })
  }

  function borrar(id){

  Swal.fire({
    title: `¿Borrar ${id}?`,
    icon: 'question',
    showCancelButton: true,
    confirmButtonColor: '#3085d6',
    cancelButtonColor: '#d33',
    confirmButtonText: 'Si, Borrar',
    cancelButtonText: "No. No Borrar"
  }).then((result) => {
    if (result.isConfirmed) {
      var url = `delete/${id}`

      $.ajax ({
          url : url,
          headers: {'X-CSRFToken': "{{csrf_token}}"},
          type: "POST",
          success: function(r){
            // alert("Borrado")
            mensaje("Borrado Satisfactoriamente","¡Atención!")
          },
          error: function(jqXHR,textStatus,error)
          {
            console.log(error)
          },
          complete: function(xhr,status){
            console.log("Finalizada")
            recargar()
          }
        })    
    }else{
      mensaje("No se borró nada")
    }
  })

  }

  function abrirModal(){
    $("#modal_edit_new").modal('show');
  }

  function cerrarModal(){
    $("#modal_edit_new").modal('hide');
  }

  $("#btnNewModal").click(function(e){
    $("#idModal").val("")
    $("#codigoModal").val("")
    $("#descripcionModal").val("")
    $("#codigoModal").focus()

    abrirModal();
  });

  $("#btnSaveModal").click(function(e){
    var c = $("#codigoModal").val()
    var d = $("#descripcionModal").val()

    saveModal(c,d)
  })

  function saveModal(codigo,desc){
    var data = {"codigo":codigo,"desc":desc}

    $.ajax({
      headers: {'X-CSRFToken': "{{csrf_token}}"},
      url:"{% url 'app:update1'%}",
      data:data,
      type:"POST",
      success: function(r){
        mensaje("Guardado Satisfatoriamente")
      },
      error: function(jqXHR,textStatus,error){
        console.log(error)
      },
      complete: function(xhr,status){
        console.log("FINALIZADO")
        recargar()
        cerrarModal()
      }
    })
  }
</script>
{% endblock%}

app/templates/app/bootstrap-table.html
{% extends 'bases/index.html' %}

{% block content %}
<table data-toggle="table"
data-url="{% url 'app:reload2' %}"
id="table"
data-show-refresh="true"
data-auto-refresh="true"
data-pagination="true"
data-show-columns="true"
data-show-columns-toggle-all="true"
data-search="true"
data-show-fullscreen="true"
data-buttons="botones"
data-click-to-select="true"
data-single-select="true"
>
    <thead>
      <tr>
        <th data-checkbox="true"></th>
        <th data-field="id">Id</th>
        <th data-field="codigo">Código</th>
        <th data-field="descripcion">Descripción</th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>

<!-- Modal -->
<div class="modal fade" id="modal_edit_new" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" 
   data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal_titulo">Agregar/Editar Registro</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form>
            <div class="form-group">
              <label for="idModal">Id</label>
              <input type="text" id="idModal" class="form-control" placeholder="Id" readonly>
            </div>
            <div class="form-group">
              <label for="codigoModal">Código</label>
              <input type="text" id="codigoModal" class="form-control" placeholder="Código">
            </div>
            <div class="form-group">
              <label for="descripcionModal">Descripción</label>
              <input type="text" id="descripcionModal" class="form-control" placeholder="Descripción">
            </div>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary" id="btnSaveModal">Guardar</button>
      </div>
    </div>
  </div>
</div>
{% endblock%}

{% block js%}
<script>
  $(document).ready( function () {
    
} );

function botones(){
  return {
    btnNuevo : {
      text: 'Nuevo Registro',
      icon: 'bi bi-plus-square-dotted',
      event: function(){

        $("#idModal").val("")
        $("#codigoModal").val("")
        $("#descripcionModal").val("")
        abrirModal()
      },
      attributes: {
        title: "Nuevo Registro"
      }
    },
    btnEdit : {
      text: 'Editar Registro',
      icon: 'bi bi-pencil-square',
      event: function(){
        var $table = $("#table")
        var obj = $table.bootstrapTable("getSelections")
        // console.log(obj[0])
        if(obj.length!=1){
          mensaje("Debe Seleccionar una Fila para Editarla","Atención!","warning")
          return
        }
        var i = obj[0].id
        var c = obj[0].codigo
        var d = obj[0].descripcion

        $("#idModal").val(i)
        $("#codigoModal").val(c)
        $("#descripcionModal").val(d)

        abrirModal()

      },
      attributes: {
        title: "Editar Registro"
      }
    },
    btnDelete: {
      text : "Borrar Registro",
      icon : "bi bi-trash3",
      event : function(){
        var $table = $("#table")
        var obj = $table.bootstrapTable("getSelections")
        if(obj.length!=1){
          mensaje("Debe Seleccionar una Fila para Eliminarla","Atención!","warning")
          return
        }

        var i = obj[0].id
        borrar(i)

      },
      attributes: {
        title: "Borrar Registro"
      }
    }
  }
}

function abrirModal(){
    $("#modal_edit_new").modal('show')
  }
  function cerrarModal(){
    $("#modal_edit_new").modal('hide')
  }

  $("#btnNewModal").click(function(e){
    $("#idModal").val("")
    $("#codigoModal").val("")
    $("#descripcionModal").val("")
    $("#codigoModal").focus()

    abrirModal()
  })

  function saveModal(codigo,desc){
    var data = {"codigo":codigo,"desc":desc}

    $.ajax({
      headers: {'X-CSRFToken': "{{csrf_token}}"},
      url:"{% url 'app:update1'%}",
      data:data,
      type:"POST",
      success: function(r){
        mensaje("Guardado Satisfatoriamente")
      },
      error: function(jqXHR,textStatus,error){
        console.log(error)
      },
      complete: function(xhr,status){
        console.log("FINALIZADO")
        recargar()
        cerrarModal()
      }
    })
  }

  $("#btnSaveModal").click(function(e){
    var c = $("#codigoModal").val()
    var d = $("#descripcionModal").val()

    saveModal(c,d)
  })

function recargar(){
  var $table = $("#table")
  $table.bootstrapTable("refresh")
}

function borrar(id){

Swal.fire({
  title: `¿Borrar ${id}?`,
  icon: 'question',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Si, Borrar',
  cancelButtonText: "No. No Borrar"
}).then((result) => {
  if (result.isConfirmed) {
    var url = `delete/${id}`

    $.ajax ({
        url : url,
        headers: {'X-CSRFToken': "{{csrf_token}}"},
        type: "POST",
        success: function(r){
          // alert("Borrado")
          mensaje("Borrado Satisfactoriamente","¡Atención!")
        },
        error: function(jqXHR,textStatus,error)
        {
          console.log(error)
        },
        complete: function(xhr,status){
          console.log("Finalizada")
          recargar()
        }
      })    
  }else{
    mensaje("No se borró nada")
  }
})

}
</script>
{% endblock %}

app/templates/app/crud.html
{% extends 'bases/index.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-6">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Código</th>
            <th scope="col">Descripción</th>
            <th scope="col">Acción</th>
          </tr>
        </thead>
        <tbody>
        </tbody>
      </table>    
    </div>
    <div class="col-6">
      <div class="row">
        <div class="col-2">
          <input type="text" id="id" class="form-control" placeholder="Id" readonly>
        </div>
        <div class="col-4">
          <input type="text" id="codigo" class="form-control" placeholder="Código">
        </div>
        <div class="col-6">
          <input type="text" id="descripcion" class="form-control" placeholder="Descripción">
        </div>
      </div>
      <hr class="mt-3 mb-3"/>
      <div class="row">
        <div class="col">
          <button type="button" id="add-row" class="btn btn-warning">Agregar</button>
          <button type="button" class="btn btn-info" id="btnCancel">Cancelar</button>
          <button type="button" class="btn btn-danger" id="btnSave">Guardar</button>
          <button type="button" class="btn btn-default" id="btnReload">Cargar</button>
          <button type="button" class="btn btn-success" id="btnEdit">Editar</button>
          <button type="button" class="btn btn-primary" id="btnSaveAll">Guardar Todo</button>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <button type="button" class="btn btn-primary" id="btnNewModal">Nuevo</button>
        </div>
    </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="modal_edit_new" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" 
   data-backdrop="static">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal_titulo">Agregar/Editar Registro</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form>
            <div class="form-group">
              <label for="idModal">Id</label>
              <input type="text" id="idModal" class="form-control" placeholder="Id" readonly>
            </div>
            <div class="form-group">
              <label for="codigoModal">Código</label>
              <input type="text" id="codigoModal" class="form-control" placeholder="Código">
            </div>
            <div class="form-group">
              <label for="descripcionModal">Descripción</label>
              <input type="text" id="descripcionModal" class="form-control" placeholder="Descripción">
            </div>
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary" id="btnSaveModal">Guardar</button>
      </div>
    </div>
  </div>
</div>
{% endblock%}

{% block js%}
<script>
  $(document).ready(function(){
    recargar()
  })
  $("#add-row").click(function(){
    var codigo = $("#codigo").val();
    var desc   = $("#descripcion").val();
    var html = `<tr><td></td><td>${codigo}</td><td>${desc}</td><td>
      <button class='btn btn-danger btn-sm btn-delete' 
      >D</button>
      <button class='btn btn-success btn-sm' 
      >E</button>
      </td></tr>`
    // console.log(html)
    if(codigo==""){
      // alert("Código Requerido")
      mensaje("Código Requerido","Atención!","warning")
      $("#codigo").focus()
      return
    }
    if(desc==""){
      // alert("Descripción Requerida")
      mensaje("Descripción Requerida","Atención!","warning")
      $("#descripcion").focus()
      return
    }
    $("table tbody").append(html)
    limpiar()
  })

  $("#btnSave").click(function(){
    $("table tbody>tr").each(function (){
      var self = $(this)
      var codigo = self.find("td:eq(1)").text().trim()
      var desc = self.find("td:eq(2)").text().trim()
      var result = codigo + " " + desc
      // console.log(self)
      
      // var data = {"codigo":codigo,"desc":desc,"csrfmiddlewaretoken" : "{{csrf_token}}"}
      var data = {"codigo":codigo,"desc":desc}
      console.log(data)

      $.ajax({
        headers: {'X-CSRFToken': "{{csrf_token}}"},
        url:"{% url 'app:update1'%}",
        data:data,
        type:"POST",
        success: function(r){
          mensaje("Guardado Satisfatoriamente")
        },
        error: function(jqXHR,textStatus,error){
          console.log(error)
        },
        complete: function(xhr,status){
          console.log("FINALIZADO")
          recargar()
        }
      })
    })
  })

  function recargar(){
    $.ajax({
        headers: {'X-CSRFToken': "{{csrf_token}}"},
        url:"{% url 'app:reload'%}",
        type:"GEST",
        success: function(r){
          console.log(r)
          datos = r.datos;
          console.log(datos)

          $("table > tbody").empty()
          var tabla = $("table")

          var rows = $.map(datos,function(value,index){
            return `<tr>
            <td>${value.id}</td><td>${value.codigo}</td>
            <td>${value.descripcion}</td>
            <td><button class='btn btn-danger btn-sm btn-delete'
              onClick="borrar(${value.id})"
              >D</button>
              <button class='btn btn-success btn-sm' 
              onClick="paraEditar(${value.id},'${value.codigo}','${value.descripcion}')"
              >E</button>
              <button class='btn btn-success btn-sm' 
              onClick="paraEditarModal(${value.id},'${value.codigo}','${value.descripcion}')"
              >E2</button>
              </td>
            </tr>`
          })
          $("table > tbody").html(rows.join(''))
        },
        error: function(jqXHR,textStatus,error){
          console.log(error)
        },
        complete: function(xhr,status){
          console.log("FINALIZADO")
        }
      })
  }

  $("#btnReload").click(function(e){
    recargar()
  })

  function borrar(id){

    Swal.fire({
      title: `¿Borrar ${id}?`,
      icon: 'question',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Si, Borrar',
      cancelButtonText: "No. No Borrar"
    }).then((result) => {
      if (result.isConfirmed) {
        var url = `delete/${id}`

        $.ajax ({
            url : url,
            headers: {'X-CSRFToken': "{{csrf_token}}"},
            type: "POST",
            success: function(r){
              // alert("Borrado")
              mensaje("Borrado Satisfactoriamente","¡Atención!")
            },
            error: function(jqXHR,textStatus,error)
            {
              console.log(error)
            },
            complete: function(xhr,status){
              console.log("Finalizada")
              recargar()
            }
          })    
      }else{
        mensaje("No se borró nada")
      }
    })
    
  }

  function limpiar(){
    $("#codigo").val("")
    $("#descripcion").val("")
    $("#id").val("")
    $("#codigo").focus()
  }

  function paraEditar(id,cod,desc)
  {
    limpiar()
    $("#id").val(id)
    $("#codigo").val(cod)
    $("#descripcion").val(desc)
  }

  $("#btnEdit").click(function(e){
    var cod = $("#codigo").val()
    var des = $("#descripcion").val()
    var id  = $("#id").val()

    var url = `edit/${id}`
    var data = {"codigo":cod,"descripcion":des}

    $.ajax ({
        url : url,
        headers: {'X-CSRFToken': "{{csrf_token}}"},
        type: "POST",
        data: data,
        success: function(r){
          // alert("Editado")
          mensaje("Guardado Satisfatoriamente")
        },
        error: function(jqXHR,textStatus,error)
        {
          console.log(error)
        },
        complete: function(xhr,status){
          console.log("Finalizada")
          limpiar()
          recargar()
        }
      })

  })
  $("#btnCancel").click(function(e){
    limpiar();
  })

  $("#btnSaveAll").click(function(){
    var datos = []

    $("table tbody>tr").each(function (){
      var self = $(this)
      var id = self.find("td:eq(0)").text().trim()
      var codigo = self.find("td:eq(1)").text().trim()
      var desc = self.find("td:eq(2)").text().trim()
      var result = codigo + " " + desc
      // console.log(self)
      
      // var data = {"codigo":codigo,"desc":desc,"csrfmiddlewaretoken" : "{{csrf_token}}"}
      var data = JSON.stringify({"codigo":codigo,"desc":desc, "id": id})
      datos.push(data)
    })
    console.log(datos)

    $.ajax({
      headers: {'X-CSRFToken': "{{csrf_token}}"},
      url:"{% url 'app:update2'%}",
      data: {'datos[]':datos},
      type:"POST",
      success: function(r){
        mensaje("Guardado Satisfatoriamente")
      },
      error: function(jqXHR,textStatus,error){
        console.log(error)
      },
      complete: function(xhr,status){
        console.log("FINALIZADO")
        recargar()
      }
    })

  })

  function abrirModal(){
    $("#modal_edit_new").modal('show')
  }
  function cerrarModal(){
    $("#modal_edit_new").modal('hide')
  }

  $("#btnNewModal").click(function(e){
    $("#idModal").val("")
    $("#codigoModal").val("")
    $("#descripcionModal").val("")
    $("#codigoModal").focus()

    abrirModal()
  })

  function saveModal(codigo,desc){
    var data = {"codigo":codigo,"desc":desc}

    $.ajax({
      headers: {'X-CSRFToken': "{{csrf_token}}"},
      url:"{% url 'app:update1'%}",
      data:data,
      type:"POST",
      success: function(r){
        mensaje("Guardado Satisfatoriamente")
      },
      error: function(jqXHR,textStatus,error){
        console.log(error)
      },
      complete: function(xhr,status){
        console.log("FINALIZADO")
        recargar()
        cerrarModal()
      }
    })
  }
  $("#btnSaveModal").click(function(e){
    var c = $("#codigoModal").val()
    var d = $("#descripcionModal").val()

    saveModal(c,d)
  })
  function paraEditarModal(id,cod,desc){
    $("#idModal").val(id)
    $("#codigoModal").val(cod)
    $("#descripcionModal").val(desc)

    abrirModal();
  }
  
</script>
{% endblock%}

app/templates/app/jtable.html
{% extends 'bases/index.html' %}

{% block content %}
<div class="container d-flex align-items.center justify-content-center">
    <div class="col-10" id="tbljtable">

    </div>
</div>
{% endblock content %}

{% block js%}
<script type="text/javascript">
    $(document).ready(function () {
        $('#tbljtable').jtable({
            title: 'CRUD jTable con Django x Daniel Bojorge (DEBS Consultores)',
            actions: {
                listAction: '{% url "app:reload4" %}',
                createAction: function (postData, jtParams) {
                    return $.Deferred(function ($dfd) {
                        $.ajax({
                            url: '{% url "app:jtable_new" %}',
                            type: 'POST',
                            data: postData,
                            headers: {'X-CSRFToken': '{{ csrf_token }}'},
                            success: function (data) {
                                $dfd.resolve(data);
                            },
                            error: function () {
                                $dfd.reject();
                            }
                        });
                    });
                },
                updateAction: function (postData, jtParams) {
                    return $.Deferred(function ($dfd) {
                        $.ajax({
                            url: '{% url "app:jtable_edit" %}',
                            type: 'POST',
                            data: postData,
                            headers: {'X-CSRFToken': '{{ csrf_token }}'},
                            success: function (data) {
                                $dfd.resolve(data);
                            },
                            error: function () {
                                $dfd.reject();
                            }
                        });
                    });
                },
                deleteAction: function (postData, jtParams) {
                    return $.Deferred(function ($dfd) {
                        $.ajax({
                            url: '{% url "app:jtable_delete" %}',
                            type: 'POST',
                            data: postData,
                            headers: {'X-CSRFToken': '{{ csrf_token }}'},
                            success: function (data) {
                                $dfd.resolve(data);
                            },
                            error: function () {
                                $dfd.reject();
                            }
                        });
                    });
                }
            },
            fields: {
                id: {
                    key: true,
                    list: true,
                    title:"Id",
                    width: "5%"
                },
                codigo: {
                    title: 'Código',
                    width: '15%'
                },
                descripcion: {
                    title: 'Descripción',
                    width: '80%'
                }
            }
        });
        $('#tbljtable').jtable('load')

    });
</script>
{% endblock %}

app/templates/app/modelo_form.html
{% extends 'bases/index.html' %}

{% block content %}
<form method="post">
  <fieldset>
    <legend>
      {% if not obj %}Nuevo{%else%}Editar{% endif%}
    </legend>
    {%csrf_token%}
    {{form}}
    
    <button type="submit" class="btn btn-primary">Guardar</button>
  </fieldset>
</form>
{% endblock%}

app/templates/app/modelo_list.html
{% extends 'bases/index.html' %}

{% block content %}
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Código</th>
        <th scope="col">Descripción</th>
        <th scope="col">Acción</th>
      </tr>
    </thead>
    <tbody>
    {% for item in obj %}
      <tr>
          <td>{{item.id}}</td>
          <td>{{item.codigo}}</td>
          <td>{{item.descripcion}}</td>
          <td>
            <a href="{% url 'app:edit' item.id %}" class="btn btn-block btn-info">Editar</a>
          </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock%}

{% block js%}
<script>
  $(document).ready( function () {
    $('table').DataTable();
} );
</script>
{% endblock %}